import json
import time
from typing import Any, Dict, List, Optional

import backoff

from ..llm.llm import call_model


class Agent:
    def __init__(
        self,
        model_name: str,
        name: str,
        temperature: float,
        provider: str = "ollama",
        sleep_time: float = 0,
        base_url: Optional[str] = None,
        api_key: Optional[str] = None,
    ) -> None:
        """Create an agent

        Args:
            model_name (str): model name
            name (str): name of this agent
            temperature (float): higher values make the output more random, while
                lower values make it more focused and deterministic
            provider (str): name of the model provider (e.g., 'ollama', 'openai')
            sleep_time (float): sleep because of rate limits
            base_url (Optional[str]): Base URL for the API calls
            api_key (Optional[str]): API key for the agent
        """
        self.model_name = model_name
        self.name = name
        self.temperature = temperature
        self.provider = provider.lower()
        self.memory_lst = []
        self.sleep_time = sleep_time
        self.base_url = base_url
        self.api_key = api_key

    @backoff.on_exception(backoff.expo, Exception, max_tries=20)
    def query(
        self,
        messages: List[Dict[str, str]],
        max_tokens: int,
        temperature: Optional[float] = None,
        json_mode: bool = True,
    ) -> str:
        """Make a query to the language model.

        Args:
            messages (List[Dict[str, str]]): Chat history in message format.
            max_tokens (int): Maximum tokens in API call.
            temperature (Optional[float]): Sampling temperature, uses default if None.
            json_mode (bool): Whether to expect JSON response.

        Raises:
            Exception: For any exceptions raised by the model call.

        Returns:
            str: The response from the model.
        """
        time.sleep(self.sleep_time)

        try:
            temp = temperature if temperature is not None else self.temperature

            # Convert messages to a single prompt string for the call_model function
            prompt = self._messages_to_prompt(messages)

            response = call_model(
                model_name=self.model_name,
                base_url=self.base_url or "",
                prompt=prompt,
                json_mode=json_mode,
                temperature=temp,
                max_tokens=max_tokens,
                api_key=self.api_key,
            )

            # Handle different response formats
            if isinstance(response, dict) and "content" in response:
                return response["content"]  # type: ignore
            else:
                try:
                    parsed_response = json.loads(response)
                    return parsed_response
                except json.JSONDecodeError:
                    return response

        except Exception as e:
            raise Exception(f"Failed to query {self.provider} service: {str(e)}")

    def _messages_to_prompt(self, messages: List[Dict[str, Any]]) -> str:
        """Convert a list of messages to a single prompt string.

        Args:
            messages (List[Dict[str, str]]): List of message dictionaries

        Returns:
            str: Combined prompt string
        """
        prompt_parts = []
        for message in messages:
            role = message.get("role", "")  # type: ignore
            content = message.get("content", "")  # type: ignore

            if role == "system":
                prompt_parts.append(f"System: {content}")
            elif role == "user":
                prompt_parts.append(f"User: {content}")
            elif role == "assistant":
                prompt_parts.append(f"Assistant: {content}")

        return "\n\n".join(prompt_parts)

    def set_meta_prompt(self, meta_prompt: str) -> None:
        """Set the meta_prompt

        Args:
            meta_prompt (str): the meta prompt
        """
        self.memory_lst.append({"role": "system", "content": f"{meta_prompt}"})

    def add_event(self, event: str) -> None:
        """Add an new event in the memory

        Args:
            event (str): string that describe the event.
        """
        self.memory_lst.append({"role": "user", "content": f"{event}"})

    def add_memory(self, memory: str, verbose: bool = False) -> None:
        """Monologue in the memory

        Args:
            memory (str): string that generated by the model in the last round.
            verbose (bool): whether to print the memory
        """
        self.memory_lst.append({"role": "assistant", "content": f"{memory}"})
        if verbose:
            print(f"----- {self.name} -----\n{memory}\n")

    def ask(self, temperature: Optional[float] = None, json_mode: bool = True) -> str:
        """Query for answer based on memory

        Args:
            temperature (Optional[float]): Override default temperature if provided
            json_mode (bool): Whether to expect JSON response

        Returns:
            str: The model's response
        """

        # Make the query
        return self.query(
            self.memory_lst,
            max_tokens=3200,
            temperature=temperature,
            json_mode=json_mode,
        )
