import json
import time
from typing import Dict, List, Optional

import backoff

from ..llm.llm import call_model


class LLMConnectionError(Exception):
    """Raised when there is a connection error with the LLM service."""

    pass


class Agent:
    def __init__(
        self,
        model_name: str,
        name: str,
        temperature: float,
        provider: str = "openai",
        sleep_time: float = 0,
    ) -> None:
        """Create an agent

        Args:
            model_name (str): model name
            name (str): name of this agent
            temperature (float): higher values make the output more random, while
                lower values make it more focused and deterministic
            provider (str): name of the model provider (e.g., 'OpenAI', 'Anthropic')
            sleep_time (float): sleep because of rate limits
        """
        self.model_name = model_name
        self.name = name
        self.temperature = temperature
        self.provider = provider.lower()
        self.memory_lst = []
        self.sleep_time = sleep_time

    @backoff.on_exception(backoff.expo, (LLMConnectionError,), max_tries=20)
    def query(
        self,
        messages: List[Dict[str, str]],
        max_tokens: int,
        temperature: Optional[float] = None,
        json_mode: bool = True,
    ) -> str:
        """Make a query to the language model.

        Args:
            messages (List[Dict[str, str]]): chat history in message format
            max_tokens (int): max token in api call
            temperature (Optional[float]): sampling temperature, uses default if None
            json_mode (bool): whether to expect JSON response

        Raises:
            LLMConnectionError: If there is a connection error with the LLM service
            OutOfQuotaException: the apikey has out of quota
            AccessTerminatedException: the apikey has been banned

        Returns:
            str: the response from the model
        """
        time.sleep(self.sleep_time)

        try:
            temp = temperature if temperature is not None else self.temperature
            response = call_model(
                model_name=self.model_name,
                provider=self.provider,
                prompt=messages,
                json_mode=json_mode,
                temperature=temp,
                max_tokens=max_tokens,
            )

            # Handle different response formats
            if isinstance(response, dict) and "content" in response:
                return response["content"]
            else:
                try:
                    parsed_response = json.loads(response)
                    return parsed_response
                except json.JSONDecodeError:
                    return response

        except ConnectionError as e:
            raise LLMConnectionError(
                f"Failed to connect to {self.provider} service: {str(e)}"
            )
        except Exception as e:
            raise e

    def set_meta_prompt(self, meta_prompt: str) -> None:
        """Set the meta_prompt

        Args:
            meta_prompt (str): the meta prompt
        """
        self.memory_lst.append({"role": "system", "content": f"{meta_prompt}"})

    def add_event(self, event: str) -> None:
        """Add an new event in the memory

        Args:
            event (str): string that describe the event.
        """
        self.memory_lst.append({"role": "user", "content": f"{event}"})

    def add_memory(self, memory: str) -> None:
        """Monologue in the memory

        Args:
            memory (str): string that generated by the model in the last round.
        """
        self.memory_lst.append({"role": "assistant", "content": f"{memory}"})
        print(f"----- {self.name} -----\n{memory}\n")

    def ask(self, temperature: Optional[float] = None, json_mode: bool = False) -> str:
        """Query for answer based on memory

        Args:
            temperature (Optional[float]): Override default temperature if provided
            json_mode (bool): Whether to expect JSON response

        Returns:
            str: The model's response
        """

        # Make the query
        return self.query(
            self.memory_lst,
            max_tokens=3200,
            temperature=temperature,
            json_mode=json_mode,
        )
